version: '3.9'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - .:/app
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  frontend:
    build:
      context: ./frontend
    container_name: streamlit-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
